# ------------------------------------------------------------------------------
#' @title Matrix for rotating shapes.
#'
#' @description This function makes a ration matrix for rotating shapes.
#' @param theta Angle of rotation (in rad).
#' @return Rotation matrix.

.rotation_matrix <- function(theta) {
  matrix(c(cos(theta), -sin(theta),
           sin(theta),  cos(theta)), nrow = 2)
}


# ------------------------------------------------------------------------------
#' @title Prepare data frame for plotting shapes
#'
#' @description This function makes a data frame for plotting shapes.
#' @param dataShapes GPML list filtered for shapes.
#' @return Data frame for plotting shapes.

.prepareShapes <- function(dataShapes){
  
  shapeFUN <- function(dataShapes){
    data.frame(CenterX = as.numeric(dataShapes$Graphics["CenterX"]),
               CenterY = as.numeric(dataShapes$Graphics["CenterY"]),
               Width = as.numeric(dataShapes$Graphics["Width"]),
               Height = as.numeric(dataShapes$Graphics["Height"]),
               ZOrder = as.numeric(dataShapes$Graphics["ZOrder"]),
               FillColor = as.character(ifelse(is.na(dataShapes$Graphics["FillColor"]),
                                               "white", paste0("#",dataShapes$Graphics["FillColor"]))),
               Alpha = as.numeric(ifelse(is.na(dataShapes$Graphics["FillColor"]),
                                         0, 1)),
               Color = as.character(ifelse(is.na(dataShapes$Graphics["Color"]),
                                           "#000000", paste0("#",dataShapes$Graphics["Color"]))),
               Label = as.character(stringr::str_remove_all(dataShapes$.attrs["TextLabel"],"\\n+$")),
               FontWeight = tolower(as.character(dataShapes$Graphics["FontWeight"])),
               FontStyle = tolower(as.character(dataShapes$Graphics["FontStyle"])),
               Valign = ifelse(as.character(dataShapes$Graphics["Valign"]) == "Middle", 0.5,
                               ifelse(as.character(dataShapes$Graphics["Valign"]) == "Top", 1,0)), 
               Align = ifelse(as.character(dataShapes$Graphics["Align"]) == "Middle", 0.5,
                              ifelse(as.character(dataShapes$Graphics["Align"]) == "Top", 1,0)), 
               ShapeType = as.character(dataShapes$Graphics["ShapeType"]), 
               Rotation = as.numeric(dataShapes$Graphics["Rotation"]),
               LineThickness = as.numeric(ifelse(is.na(dataShapes$Graphics["LineThickness"]),
                                                 1, dataShapes$Graphics["LineThickness"]))/2,
               LineStyle = as.character(ifelse(is.na(dataShapes$Graphics["LineStyle"]),
                                               "solid", tolower(dataShapes$Graphics["LineStyle"]))),
               nLine = ifelse(sum(stringr::str_detect(unlist(dataShapes[which(names(dataShapes) == "Attribute")]), "Double")) == 0, "Single", "Double"),
               GraphId = as.character(dataShapes$.attrs["GraphId"])
    )
  }
  shapes_df <- do.call(rbind, lapply(dataShapes, shapeFUN))
  
  # Change font face
  shapes_df$FontFace <- "plain"
  shapes_df$FontFace[(!is.na(shapes_df$FontWeight) & is.na(shapes_df$FontStyle))] <- shapes_df$FontWeight[(!is.na(shapes_df$FontWeight) & is.na(shapes_df$FontStyle))]
  shapes_df$FontFace[(is.na(shapes_df$FontWeight) & !is.na(shapes_df$FontStyle))] <- shapes_df$FontStyle[(is.na(shapes_df$FontWeight) & !is.na(shapes_df$FontStyle))]
  shapes_df$FontFace[((shapes_df$FontWeight == "bold") & (shapes_df$FontStyle == "italic")) |
                       ((shapes_df$FontWeight == "italic") & (shapes_df$FontStyle == "bold"))] <- "bold.italic"
  
  
  # Change line style
  shapes_df$LineStyle <- ifelse(shapes_df$LineStyle == "broken",
                                "dashed", "solid")
  
  #shapes_df$Text <- iconv(shapes_df$Text, from = 'UTF-8', to = 'ASCII//TRANSLIT')
  #shapes_df$Text[(grepl("[^ -~]", shapes_df$Text)) & (!grepl("\\n", shapes_df$Text))] <- NA
  return(shapes_df)
}


# ------------------------------------------------------------------------------
#' @title Draw shapes
#'
#' @description This function adds shapes to the pathway image.
#' @param shapes_df A data frame with shape information, as generated by the .prepareShapes() function.
#' @return A plot with shapes.

.drawShapes <- function(shapes_df){
  
  # Filter for non-cell components
  shapes_df <- shapes_df[!(shapes_df$ShapeType %in% c("Mitochondria",
                                                      "Sarcoplasmic Reticulum",
                                                      "Endoplasmic Reticulum",
                                                      "Golgi Apparatus")),]
  shapes_df$Rotation[is.na(shapes_df$Rotation)] <- 0
  polygon_df_plot <- NULL
  line_df_plot <- NULL
  rect_df_plot <- NULL
  #shapes_df <- dplyr::arrange(shapes_df, by = ZOrder)
  for (i in 1:nrow(shapes_df)){
    
    # Define variables
    width <- shapes_df$Width[i]
    height <- shapes_df$Height[i]
    centerX <- shapes_df$CenterX[i]
    centerY <- shapes_df$CenterY[i]
    rotation <- shapes_df$Rotation[i]
    alpha <- shapes_df$Alpha[i]
    fillcolor <- shapes_df$FillColor[i]
    edgecolor <- shapes_df$Color[i]
    thickness <- shapes_df$LineThickness[i]
    type <- shapes_df$ShapeType[i]
    nLine <- shapes_df$nLine[i]
    linestyle <- shapes_df$LineStyle[i]
    valign <- shapes_df$Valign[i]
    align <- shapes_df$Align[i]
    
    #==========================================================================#
    # Prepare polygons
    #==========================================================================#
    if (type %in% c("Triangle", "RoundedRectangle", "Rectangle",
                    "Pentagon", "Hexagon", "Oval", "mim-degradation")){
      n_corners <- NULL
      if (type == "Triangle"){
        starting_angle = 0
        max_angle = 2*pi
        n_corners = 3
        adj <- 1
        
        # The width and coordinates of the triangle are not correctly defined 
        # in the GPML file, so we need to do some slight adjustment
        width <- width*1.25
        centerX <- centerX + 0.07*cos(rotation)*width
        centerY <- centerY + 0.07*sin(rotation)*height
      }
      if (type == "RoundedRectangle" |
          type == "Rectangle"){
        starting_angle = 0.25*pi
        max_angle = 2*pi
        n_corners = 4
        adj <- sqrt(2)
      }
      if (type == "Pentagon"){
        starting_angle = 0
        max_angle = 2*pi
        n_corners = 5
        adj <- 1
      }
      if (type == "Hexagon"){
        starting_angle = 0
        max_angle = 2*pi
        n_corners = 6
        adj <- 1
      }
      if (type == "Oval"){
        starting_angle = 0
        max_angle = 2*pi
        n_corners = 100
        adj <- 1
      }
      
      if (type == "mim-degradation"){
        starting_angle = 0
        max_angle = 2*pi
        n_corners = 100
        adj <- 1
        width <- 0.7*width
        height <- 0.7*height
      }
      
      if (!is.null(n_corners)){
        
        # Create angle offsets (no rotation yet)
        angle <- seq(0, max_angle, length.out = n_corners + 1)[-1]  # remove duplicate 2pi
        x <- rep(NA, n_corners)
        y <- rep(NA, n_corners)
        corner_coords <- matrix(NA, nrow = n_corners, ncol = 2)
        for (c in 1:n_corners){
          
          corner_coords[c,1] <- adj*width/2 * cos(angle[c] + starting_angle)
          corner_coords[c,2] <- adj*height/2 * sin(angle[c] + starting_angle)
          
        }
        
        # Apply rotation matrix
        rot_mat <- .rotation_matrix(-1*rotation)
        rotated_coords <- t(rot_mat %*% t(corner_coords))
        
        # Translate to center
        x <- rotated_coords[,1] + centerX
        y <- rotated_coords[,2] + centerY
        
        
        # Single line
        if (nLine == "Single"){
          temp <- data.frame(angle = angle,
                             x = x,
                             y = y,
                             id = i,
                             Alpha = alpha,
                             FillColor = fillcolor,
                             EdgeColor = edgecolor,
                             LineThickness = thickness*3,
                             LineStyle = linestyle,
                             Valign = valign,
                             Align = align)
          # Double line
        } else{
          temp1 <- data.frame(angle = angle,
                              x = x,
                              y = y,
                              id = i,
                              Alpha = alpha,
                              FillColor = fillcolor,
                              EdgeColor = edgecolor,
                              LineThickness = thickness*10,
                              LineStyle = linestyle,
                              Valign = valign,
                              Align = align)
          temp2 <- data.frame(angle = angle,
                              x = x,
                              y = y,
                              id = paste0(i, ".2"),
                              Alpha = 0,
                              FillColor = "white",
                              EdgeColor = "white",
                              LineThickness = thickness*2,
                              LineStyle = linestyle,
                              Valign = valign,
                              Align = align)
          temp <- rbind.data.frame(temp1, temp2)
        }
        
        
        polygon_df_plot <- rbind.data.frame(polygon_df_plot, temp)
      }
      
    }
    
    #==========================================================================#
    # Prepare lines
    #==========================================================================#
    if (type %in% c("mim-degradation", "Arc")){
      
      if (type == "mim-degradation"){
        xstart <- 0.7*width
        xend <- -0.7*width
        ystart <- 0.7*height
        yend <- -0.7*height
        
        # Apply rotation matrix
        rot_mat <- .rotation_matrix(-1*rotation)
        rotated_coords <- t(rot_mat %*% t(matrix(c(xstart,xend,ystart,yend), nrow = 2)))
        
        # Translate to center
        x <- rotated_coords[,1] + centerX
        y <- rotated_coords[,2] + centerY
        
        temp <- data.frame(
          x1 = x[-length(x)],
          x2 = x[-1],
          y1 = y[-length(y)],
          y2 = y[-1],
          x = x,
          y = y,
          id = i,
          Alpha = 1,
          FillColor = fillcolor,
          EdgeColor = edgecolor,
          LineThickness = thickness*2,
          LineStyle = linestyle,
          Valign = valign,
          Align = align)
        
      }
      
      if (type == "Arc"){
        starting_angle = 0
        max_angle = pi
        n_corners = 100
        adj <- 1
        
        # Create angle offsets (no rotation yet)
        angle <- seq(0, max_angle, length.out = n_corners + 1)[-1]  # remove duplicate 2pi
        x <- rep(NA, n_corners)
        y <- rep(NA, n_corners)
        corner_coords <- matrix(NA, nrow = n_corners, ncol = 2)
        for (c in 1:n_corners){
          
          corner_coords[c,1] <- adj*width/2 * cos(angle[c] + starting_angle)
          corner_coords[c,2] <- adj*height/2 * sin(angle[c] + starting_angle)
          
        }
        
        # Apply rotation matrix
        rot_mat <- .rotation_matrix(-1*rotation)
        rotated_coords <- t(rot_mat %*% t(corner_coords))
        
        # Translate to center
        x <- rotated_coords[,1] + centerX
        y <- rotated_coords[,2] + centerY
        
        temp <- data.frame(
          x1 = x[-length(x)],
          x2 = x[-1],
          y1 = y[-length(y)],
          y2 = y[-1],
          id = i,
          Alpha = 1,
          FillColor = fillcolor,
          EdgeColor = edgecolor,
          LineThickness = thickness*2,
          LineStyle = linestyle,
          Valign = valign,
          Align = align)
        
      }
      line_df_plot <- rbind.data.frame(line_df_plot, temp)
    }
  }
  
  
  #==========================================================================#
  # Plot Shapes
  #==========================================================================#
  
  # Plot polygons
  if (length(polygon_df_plot) > 0){
    
    for (id in unique(polygon_df_plot$id)){
      polygon_df_plot1 <- polygon_df_plot[polygon_df_plot$id == id,]
      polygon(x = polygon_df_plot1$x,
              y = -1 *polygon_df_plot1$y,
              col = adjustcolor(polygon_df_plot1$FillColor[1], alpha.f = polygon_df_plot1$Alpha[1]),
              border = polygon_df_plot1$EdgeColor[1],
              lwd = polygon_df_plot1$LineThickness[1],
              lty =  polygon_df_plot1$LineStyle[1])
    }
    
  }
  
  # Plot lines
  if  (length(line_df_plot) > 0){
    arrows(x0 = line_df_plot$x1, x1 = line_df_plot$x2,
           y0 = -1*line_df_plot$y1, y1 = -1*line_df_plot$y2,
           lty = line_df_plot$LineStyle, code = 0,
           col = line_df_plot$EdgeColor,
           lwd = line_df_plot$LineThickness)
  }
  
  # Plot text labels
  if (length(shapes_df$Label[!is.na(shapes_df$Label)]) > 0){
    
    # Change NA alignment values to default values
    labels_df <- shapes_df[!is.na(shapes_df$Label),]
    labels_df$Align[is.na(labels_df$Align)] <- 0.5
    labels_df$Valign[is.na(labels_df$Valign)] <- 1
    
    # position <- NULL
    # if (labels_df$Align == 0){
    #   position <- 4
    # }
    # if (labels_df$Align == 1){
    #   position <- 2
    #}
    
    # Offset when aligning the labels to the top/bottom or right/left
    x_offset <- 10
    y_offset <- 30
    
    # Change fontface to numeric values
    labels_df$FontFace[is.na(labels_df$FontFace)] <- 1
    labels_df$FontFace[labels_df$FontFace == "plain"] <- 1
    labels_df$FontFace[labels_df$FontFace == "bold"] <- 2
    labels_df$FontFace[labels_df$FontFace == "italic"] <- 3
    labels_df$FontFace[labels_df$FontFace== "bold.italic"] <- 4
    
    text(x = labels_df$CenterX+(labels_df$Align-0.5)*labels_df$Width+(0.5-labels_df$Align)*x_offset,
         y = -1*(labels_df$CenterY-(labels_df$Valign-0.5)*labels_df$Height-(0.5-labels_df$Valign)*y_offset),
         adj = c(labels_df$Align, labels_df$Valign),
         labels = labels_df$Label,
         cex = labels_df$FontSize/12.5,
         col = labels_df$Color,
         #pos = position,
         font = as.numeric(labels_df$FontFace))
  }
}


# ------------------------------------------------------------------------------
#' @title Draw braces
#'
#' @description This function adds braces to the pathway image.
#' @param shapes_df A data frame with shape information, as generated by the .prepareShapes() function.
#' @return A plot with braces.

.drawBraces <- function(braces_df){
  
  # Order the data frame by the Z-order
  braces_df <- dplyr::arrange(braces_df, by = ZOrder)
  
  # Number of point used for drawing the brace
  npoints = 100
  
  # Collect coordinates of each brace
  plot_all <- NULL
  for (i in 1:nrow(braces_df)){
    
    # Set start, mid, end coordinates
    xstart <- -0.5*braces_df$Width[i]
    ystart <- -0.5*braces_df$Height[i]
    xmid <- 0
    ymid <- 0
    xend <- 0.5*braces_df$Width[i]
    yend <- 0.5*braces_df$Height[i]
    
    # Set radius of quarter circles
    xradius <- braces_df$Width[i]/4
    yradius <- braces_df$Height[i]/2
    
    # Function to create a circle (of which only quarters will be used later)
    circle <- function(x, y){
      positions <- seq(0, 2*pi, length.out=npoints)
      return( data.frame(x = x + xradius * cos(positions), y = y + yradius * sin(positions)) )
    }
    
    # Create brace data points by calculating 4 quarter circles
    rounds <- list(
      data.frame(x=xstart,y=ystart),
      leftQuartercircle = circle(xstart+xradius, ystart)[seq(npoints/4+1, npoints/2),],
      leftmidQuartercircle = circle(xmid-xradius, yend)[seq(npoints/4*3+1, npoints),],
      data.frame(x=xmid,y=yend),
      rightmidQuartercircle = circle(xmid+xradius, yend)[seq(npoints/2+1, npoints/4*3),],
      rightQuartercircle = circle(xend-xradius, ystart)[seq(1,npoints/4),],
      data.frame(x=xend,y=ystart)
    )
    
    output <- do.call(rbind, rounds)
    output <- output[order(output$x),]
    output$y <- output$y
    rownames(output) <- NULL
    
    # Perform rotation
    rot_mat <- .rotation_matrix(-1*braces_df$Rotation[i]+pi)
    rotated_coords <- data.frame(t(rot_mat %*% t(output)))
    colnames(rotated_coords) <- c("x", "y")
    rotated_coords$x <- rotated_coords$x + braces_df$CenterX[i]
    rotated_coords$y <- rotated_coords$y + braces_df$CenterY[i]
    rotated_coords$group <- i
    rotated_coords$color <- braces_df$Color[i]
    rotated_coords$thickness <- braces_df$LineThickness[i]
    
    
    # Collect all cordinates
    plot_all <- rbind.data.frame(plot_all, rotated_coords)
    
  }
  # Make plot
  lines(x = plot_all$x, y = -1*plot_all$y, 
        col = plot_all$color,
        lwd = plot_all$thickness*2)
}


# ------------------------------------------------------------------------------
#' @title Draw cell components
#'
#' @description This function adds cell components to the pathway image.
#' @param shapes_df A data frame with shape information, as generated by the .prepareShapes() function.
#' @return A plot with cell components.

.drawCellComponents <- function(shapes_df){
  
  # Filter for cell components
  shapes_df <- shapes_df[shapes_df$ShapeType %in% c("Mitochondria",
                                                    "Sarcoplasmic Reticulum",
                                                    "Endoplasmic Reticulum",
                                                    "Golgi Apparatus"),]
  
  # Plot component by component
  for (i in 1:nrow(shapes_df)){
    
    # Define variables
    width <- shapes_df$Width[i]
    height <- shapes_df$Height[i]
    centerX <- shapes_df$CenterX[i]
    centerY <- shapes_df$CenterY[i]
    rotation <- shapes_df$Rotation[i]
    alpha <- shapes_df$Alpha[i]
    fillcolor <- shapes_df$FillColor[i]
    edgecolor <- shapes_df$EdgeColor[i]
    thickness <- shapes_df$LineThickness[i]
    type <- shapes_df$ShapeType[i]
    nLine <- shapes_df$nLine[i]
    linestyle <- "solid"
    
    # Add mitochondria
    if (type %in% c("Mitochondria")){
      newWidth <- abs(sin(rotation)*height) + abs(cos(rotation)*width)
      newHeight <- abs(cos(rotation)*height) + abs(sin(rotation)*width)
      xmin = centerX - 0.5*newWidth
      xmax = centerX + 0.5*newWidth 
      ymin = centerY - 0.5*newHeight
      ymax = centerY + 0.5*newHeight
      
      img <- magick::image_read("pathwayElements/Mitochondria.png")
      #img <- magick::image_read("C:/Users/jarno/GitHub/ShinyPath/rWikiPathways-devel/inst/pathwayElements/Mitochondria.png")
      img <- magick::image_rotate(img, (rotation*180)/pi)
      img <-  magick::image_transparent(img, color = "white")
      rasterImage(img, xmin, -ymax, xmax, -ymin)
      
    }
    
    # Add sacroplasmic reticulum
    if (type %in% c("Sarcoplasmic Reticulum")){
      height <- height*1.1
      newWidth <- abs(sin(rotation)*height) + abs(cos(rotation)*width)
      newHeight <- abs(cos(rotation)*height) + abs(sin(rotation)*width)
      xmin = centerX - 0.5*newWidth
      xmax = centerX + 0.5*newWidth 
      ymin = centerY - 0.5*newHeight
      ymax = centerY + 0.5*newHeight
      
      img <- magick::image_read("pathwayElements/SR.png")
      #img <- magick::image_read("C:/Users/jarno/GitHub/ShinyPath/rWikiPathways-devel/inst/pathwayElements/SR.png")
      img <- magick::image_rotate(img, (rotation*180)/pi)
      img <-  magick::image_transparent(img, color = "white")
      rasterImage(img, xmin, -ymax, xmax, -ymin)
    }
    
    # Add endoplasmic reticulum
    if (type %in% c("Endoplasmic Reticulum")){
      newWidth <- abs(sin(rotation)*height) + abs(cos(rotation)*width)
      newHeight <- abs(cos(rotation)*height) + abs(sin(rotation)*width)
      xmin = centerX - 0.5*newWidth
      xmax = centerX + 0.5*newWidth 
      ymin = centerY - 0.5*newHeight
      ymax = centerY + 0.5*newHeight
      
      img <- magick::image_read("pathwayElements/ER.png")
      #img <- magick::image_read("C:/Users/jarno/GitHub/ShinyPath/rWikiPathways-devel/inst/pathwayElements/ER.png")
      img <- magick::image_rotate(img, (rotation*180)/pi)
      img <-  magick::image_transparent(img, color = "white")
      rasterImage(img, xmin, -ymax, xmax, -ymin)
    }
    
    # Add golgi apparatus
    if (type %in% c("Golgi Apparatus")){
      height <- height*1.05
      newWidth <- abs(sin(rotation)*height) + abs(cos(rotation)*width)
      newHeight <- abs(cos(rotation)*height) + abs(sin(rotation)*width)
      xmin = centerX - 0.5*newWidth
      xmax = centerX + 0.5*newWidth 
      ymin = centerY - 0.5*newHeight
      ymax = centerY + 0.5*newHeight
      
      img <- magick::image_read("pathwayElements/Golgi.png")
      #img <- magick::image_read("C:/Users/jarno/GitHub/ShinyPath/rWikiPathways-devel/inst/pathwayElements/Golgi.png")
      img <- magick::image_rotate(img, (rotation*180)/pi)
      img <-  magick::image_transparent(img, color = "white")
      rasterImage(img, xmin, -ymax, xmax, -ymin)
    }
  }
}

