# ------------------------------------------------------------------------------
#' @title Prepare data frame for plotting states
#'
#' @description This function makes a data frame for plotting states.
#' @param dataStates A GPML list filtered for states.
#' @param nodes_df A data frame with node information,
#' as generated by the .prepareNodes() function.
#' @return A data frame for plotting states.
#' @noRd

.prepareStates <- function(dataStates, nodes_df){

    stateFUN <- function(dataStates){
        data.frame(
            RelX = as.numeric(dataStates$Graphics["RelX"]),
            RelY = as.numeric(dataStates$Graphics["RelY"]),
            Width = as.numeric(dataStates$Graphics["Width"]),
            Height = as.numeric(dataStates$Graphics["Height"]),
            ShapeType = as.character(dataStates$Graphics["ShapeType"]),
            TextLabel = as.character(dataStates$.attrs["TextLabel"]),
            GraphId = as.character(dataStates$.attrs["GraphId"]),
            GraphRef = as.character(dataStates$.attrs["GraphRef"])
        )
    }
    states_df <- do.call(rbind, lapply(dataStates, stateFUN))
    states_df <- dplyr::left_join(
        states_df, nodes_df,
        by = c("GraphRef" = "GraphId"))

    states_df_plot <- data.frame(
        Y = states_df$CenterY + 0.5*states_df$Height.y*states_df$RelY,
        X = states_df$CenterX + 0.5*states_df$Width.y*states_df$RelX,
        Width = states_df$Width.x,
        Height = states_df$Height.x,
        ShapeType = states_df$ShapeType.x,
        TextLabel = states_df$TextLabel,
        GraphId = states_df$GraphId
    )
    states_df_plot$ShapeType[is.na(states_df_plot$ShapeType)] <- "Square"
    return(states_df_plot)
}


# ------------------------------------------------------------------------------
#' @title Draw states
#'
#' @description This function adds states to the pathway image.
#' @param states_df A data frame with states information,
#' as generated by the .prepareStates() function.
#' @return A plot with states.
#' @noRd

.drawStates <- function(states_df){
    starting_angle <- 0
    n_corners <- 100
    adj <- 1
    polygon_df_plot <- NULL
    polygon_df_plot <- NULL
    for (i in seq_len(nrow(states_df))){
        # Define variables
        centerX <- states_df$X[i]
        centerY <- states_df$Y[i]
        textLabel <- states_df$TextLabel[i]
        graphId <- states_df$GraphId[i]
        param <- .getStateParameters(states_df, i)

        if (!is.null(param)){
            starting_angle <- param[["starting_angle"]]
            max_angle <- param[["max_angle"]]
            n_corners <- param[["n_corners"]]
            adj <- param[["adj"]]
            rotation <- param[["rotation"]]
            width <- param[["width"]]
            height <- param[["height"]]
            # Create angle offsets (no rotation yet)
            angle <- seq(0, max_angle, length.out = n_corners + 1)[-1]
            corner_coords <- matrix(NA, nrow = n_corners, ncol = 2)
            for (c in seq_len(n_corners)){
                corner_coords[c,1] <- adj*width/2 *
                    cos(angle[c] + starting_angle)
                corner_coords[c,2] <- adj*height/2 *
                    sin(angle[c] + starting_angle)}
            # Apply rotation matrix
            rot_mat <- .rotation_matrix(-1*rotation)
            rotated_coords <- t(rot_mat %*% t(corner_coords))
            # Translate to center
            x <- rotated_coords[,1] + centerX
            y <- rotated_coords[,2] + centerY
            temp <- data.frame(angle = angle, x = x, y = y, id = i)
        }else{temp <- NULL}
        polygon_df_plot <- rbind.data.frame(polygon_df_plot, temp)
    }
    graphics::polygon(
        x = polygon_df_plot$x, y = -1 *polygon_df_plot$y,
        col = "white", border ="black")
    graphics::text(
        x = states_df$X,y = -1*states_df$Y,
        labels = states_df$TextLabel,col = "black")
}


.getStateParameters <- function(states_df, i){
    width <- states_df$Width[i]
    height <- states_df$Height[i]
    type <- states_df$ShapeType[i]
    if (type == "Square"){
        return(list(
            starting_angle = 0.25*pi, max_angle = 2*pi,
            n_corners = 4, adj = sqrt(2), rotation = 0,
            width = width, height = height))
    }
    else if (type == "Triangle"){
        return(list(
            starting_angle = 0, max_angle = 2*pi,
            n_corners = 3, adj = 1, rotation = 90,
            width = width, height = height))
    }
    else if (type == "RoundedRectangle" | type == "Rectangle"){
        return(list(
            starting_angle = 0.25*pi, max_angle = 2*pi,
            n_corners = 4, adj = sqrt(2), rotation = 0,
            width = width, height = height))
    }
    else if (type == "Pentagon"){
        return(list(
            starting_angle = 0.25*pi, max_angle = 2*pi,
            n_corners = 5, adj = 1, rotation = 0,
            width = width, height = height))
    }
    else if (type == "Hexagon"){
        return(list(
            starting_angle = 0, max_angle = 2*pi,
            n_corners = 6, adj = 1, rotation = 0,
            width = width, height = height))
    }
    else if (type == "Oval"){
        return(list(
            starting_angle = 0, max_angle = 2*pi,
            n_corners = 100, adj = 1, rotation = 0,
            width = width, height = height))
    }
    else if (type == "mim-degradation"){
        return(list(
            starting_angle = 0, max_angle = 2*pi,
            n_corners = 100, adj = 1, rotation = 0,
            width = 0.7*width, height = 0.7*height))
    }
    else{return(NULL)}
}
