# ------------------------------------------------------------------------------
#' @title Prepare data frame for plotting nodes
#'
#' @description This function makes a data frame for plotting nodes.
#' @param dataNodes A GPML list filtered for nodes.
#' @return A data frame for plotting nodes.
#' @noRd

.prepareNodes <- function(dataNodes){

    # Extract nodes
    nodes_df <- do.call(rbind, lapply(dataNodes, .nodeFUN))

    # Change font face
    nodes_df$FontFace <- "plain"
    nodes_df$FontFace[(
        !is.na(nodes_df$FontWeight) & is.na(nodes_df$FontStyle))] <-
        nodes_df$FontWeight[(
            !is.na(nodes_df$FontWeight) & is.na(nodes_df$FontStyle))]
    nodes_df$FontFace[(
        is.na(nodes_df$FontWeight) & !is.na(nodes_df$FontStyle))] <-
        nodes_df$FontStyle[(
            is.na(nodes_df$FontWeight) & !is.na(nodes_df$FontStyle))]
    nodes_df$FontFace[(
        (nodes_df$FontWeight == "bold") &
            (nodes_df$FontStyle == "italic")) | (
                (nodes_df$FontWeight == "italic") &
                    (nodes_df$FontStyle == "bold"))] <- "bold.italic"

    # Change line style
    nodes_df$LineStyle <- ifelse(
        nodes_df$LineStyle == "broken",
        "dashed", "solid")

    return(nodes_df)
}

.nodeFUN <- function(dataNodes){
    data.frame(
        CenterX = as.numeric(dataNodes$Graphics["CenterX"]),
        CenterY = as.numeric(dataNodes$Graphics["CenterY"]),
        Width = as.numeric(dataNodes$Graphics["Width"]),
        Height = as.numeric(dataNodes$Graphics["Height"]),
        ZOrder = as.numeric(dataNodes$Graphics["ZOrder"]),
        FillColor = as.character(ifelse(
            is.na(dataNodes$Graphics["FillColor"]) |
                dataNodes$Graphics["FillColor"] == "Transparent",
            "white", paste0("#",dataNodes$Graphics["FillColor"]))),
        Alpha = 1,
        Color = as.character(ifelse(
            is.na(dataNodes$Graphics["Color"]),
            "#000000", paste0("#", dataNodes$Graphics["Color"]))),
        Label = as.character(stringr::str_remove_all(
            dataNodes$.attrs["TextLabel"],"\\n+$")),
        FontSize = as.numeric(dataNodes$Graphics["FontSize"]),
        FontWeight = tolower(as.character(dataNodes$Graphics["FontWeight"])),
        FontStyle = tolower(as.character(dataNodes$Graphics["FontStyle"])),
        Valign = ifelse(
            as.character(dataNodes$Graphics["Valign"]) == "Middle",
            0.5,ifelse(as.character(dataNodes$Graphics["Valign"])=="Top",1,0)),
        Align = ifelse(
            as.character(dataNodes$Graphics["Align"]) == "Middle",
            0.5,ifelse(as.character(dataNodes$Graphics["Align"])=="Top",1,0)),
        ShapeType = ifelse(
            is.na(as.character(dataNodes$Graphics["ShapeType"])),
            "Rectangle", as.character(dataNodes$Graphics["ShapeType"])),
        Rotation = 0,
        LineThickness = as.numeric(ifelse(
            is.na(dataNodes$Graphics["LineThickness"]),
            1,dataNodes$Graphics["LineThickness"]))/2,
        LineStyle = as.character(ifelse(
            is.na(dataNodes$Graphics["LineStyle"]),
            "solid", tolower(dataNodes$Graphics["LineStyle"]))),
        nLine = ifelse(sum(stringr::str_detect(unlist(
            dataNodes[which(names(dataNodes) == "Attribute")]
        ),"Double")) == 0, "Single", "Double"),
        NodeType = as.character(dataNodes$.attrs["Type"]),
        Database = as.character(dataNodes$Xref["Database"]),
        ID = as.character(dataNodes$Xref["ID"]),
        GroupRef = as.character(dataNodes$.attrs["GroupRef"]),
        GraphId = as.character(dataNodes$.attrs["GraphId"]),
        GraphId1 = dataNodes$ID)
}

# ------------------------------------------------------------------------------
#' @title Draw nodes
#'
#' @description This function adds nodes to the pathway image.
#' @param nodes_df A data frame with node information,
#'  as generated by the .prepareNodes() function.
#' @param colors_df A data frame with coloring information,
#'  as generated by .mapColors() function.
#' @return A plot with nodes.
#' @noRd

.drawNodes <- function(nodes_df, colors_df){
    nodes_df$Align[is.na(nodes_df$Align)] <- 0.5
    nodes_df$Valign[is.na(nodes_df$Valign)] <- 1

    # Set edge color to black, unless no expression data is plotted on
    # that specific node type
    if (length(colors_df) > 0){
        exNodeType <- rownames(
            table(
                colors_df$NodeType,
                colors_df$Scale))[
                    rowSums(table(colors_df$NodeType, colors_df$Scale)) == 0]
        nodes_df$Color[!(nodes_df$NodeType %in% exNodeType)] <- "#000000"
    }

    # Set font weight
    nodes_df$FontFace[is.na(nodes_df$FontFace)] <- 1
    nodes_df$FontFace[nodes_df$FontFace == "plain"] <- 1
    nodes_df$FontFace[nodes_df$FontFace == "bold"] <- 2
    nodes_df$FontFace[nodes_df$FontFace == "italic"] <- 3
    nodes_df$FontFace[nodes_df$FontFace == "bold.italic"] <- 4

    # Offset when aligning the labels to the top/bottom or right/left
    x_offset <- 10
    y_offset <- 30

    # Make plot
    graphics::rect(
        xleft = nodes_df$CenterX - 0.5* nodes_df$Width,
        ybottom = -1*( nodes_df$CenterY - 0.5*nodes_df$Height),
        xright =  nodes_df$CenterX + 0.5*nodes_df$Width,
        ytop =  -1*( nodes_df$CenterY + 0.5* nodes_df$Height),
        col = grDevices::adjustcolor(nodes_df$FillColor, 0),
        border = nodes_df$Color,
        lty = nodes_df$LineStyle,
        lwd = nodes_df$LineThickness*2)
    graphics::text(
        x = nodes_df$CenterX+(nodes_df$Align-0.5)*
            nodes_df$Width+(0.5-nodes_df$Align)*x_offset,
        y = -1*(nodes_df$CenterY-(nodes_df$Valign-0.5)*
                    nodes_df$Height-(0.5-nodes_df$Valign)*y_offset),
        adj = c(nodes_df$Align, nodes_df$Valign),
        labels = nodes_df$Label,
        cex = nodes_df$FontSize/12.5,
        col = nodes_df$Color,
        font = as.numeric(nodes_df$FontFace))
}


